### ISSUE TITLE
python插件可选忽略某些库不安装

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1181]
### 您认为还缺少什么?如何解决您的问题?

可以在`pyproject.toml`写个配置项，像这样
感觉可以上正则匹配
```toml
[tool.llbds]
ignore-deps = ["llpy-helper-lib"]
```
